Improve location handling and offline output

diff --git a/carbon-client/carbon b/carbon-client/carbon
--- a/carbon-client/carbon
+++ b/carbon-client/carbon
@@ -285,24 +285,20 @@ if [ $INTERNET == "true" ] && [ -z $LOCATION ] ; then
         echo "# Validating Location"
         ask_question LOCATION $LOCATION
         while ! echo "$VALID_LOCATIONS" |grep -q -w "$LOCATION" ; do
-            echo "Location not provided or invalid. Must be a 3 letter country code as per the ISO 3166-1 alpha-3 standard."
-            echo "The script failed to identify location correctly due to an issue (e.g. no internet connection) and"
-            echo "the environment variable LOCATION is invalid or has not been provided."
-            echo
-            echo "Valid locations are:"
-            echo "    $VALID_LOCATIONS"
+            echo "Location is invalid. Must be a 3 letter country code as per the ISO 3166-1 alpha-3 standard."
             echo
             ask_question LOCATION $LOCATION
         done
     fi
+elif [ -z $ACCEPT_DEFAULTS ] ; then
+    while ! echo "$VALID_LOCATIONS" |grep -q -w "$LOCATION" ; do
+        echo "Location is invalid. Must be a 3 letter country code as per the ISO 3166-1 alpha-3 standard."
+        echo
+        ask_question LOCATION $LOCATION
+    done
 else 
     if ! echo "$VALID_LOCATIONS" |grep -q -w "$LOCATION" ; then
-        echo "Location not provided or invalid. Must be a 3 letter country code as per the ISO 3166-1 alpha-3 standard."
-        echo "The script failed to identify location correctly due to an issue (e.g. no internet connection) and"
-        echo "the environment variable LOCATION is invalid or has not been provided."
-        echo
-        echo "Valid locations are:"
-        echo "    $VALID_LOCATIONS"
+        echo "Location is invalid. Must be a 3 letter country code as per the ISO 3166-1 alpha-3 standard."
         exit 1
     fi
 fi
@@ -347,8 +343,9 @@ case $action in
             PAYLOAD_FILE="$DIR/payload-$UUID.json"
             echo "$PAYLOAD" >> $PAYLOAD_FILE
             if [ -z $QUIET ] ; then
-                echo "This command has been unable to reach the Internet so is unable to send system specs to the
-    carbon leaderboard."
+                echo "This command has been set to offline mode or has been unable to reach the Internet"
+                echo "so is unable to send system specs to the carbon leaderboard."
+                echo
                 echo "Upload $PAYLOAD_FILE to $LEADERBOARD_URL to get your carbon calculations."
             fi
         fi
